package main

import (
    "encoding/json"
    "fmt"
    "io/ioutil"
    "os"
)

/** File formulate

{
  "version": 1,
  "endpoints": {
    "http://etcetc:3003": {
      "last-fetch": 123123123,
      "fetches": [
          {
            "result-status": "200",
            "result-len":1231231,
            "result-roundtrip":1231231
          }
        ]
    }
  }
}

*/

type HttpAPIResult struct {
  ResultStatus    string `json:"result-status"`
  ResultLen       int    `json:"result-len"`
  ResultRoundtrip int    `json:"result-roundtrip"`
}

type HttpServiceDocument struct {
  LastFetch int `json:"last-fetch"`
  Fetches   []HttpAPIResult  `json:"fetches"`
}

type AutoGenerated struct {
	Version   int `json:"version"`
	Endpoints map[string]HttpServiceDocument `json:"endpoints"`
}

func loadRecords() AutoGenerated {
  raw, err := ioutil.ReadFile("./api_records.json")
  if err != nil {
    fmt.Println(err.Error())
    os.Exit(1)
  } else {
    // populate with default data here
  }

  var c AutoGenerated
  json.Unmarshal(raw, &c)

  return c
}
